steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/t28-biddata/game28-api-rust:configurable-k-v3
      - .

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/t28-biddata/game28-api-rust:configurable-k-v3

timeout: 2400s
