steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - backend/Dockerfile
      - --tag
      - ${_IMAGE_URI}
      - .

images:
  - ${_IMAGE_URI}

options:
  machineType: E2_HIGHCPU_8

timeout: 1800s
