steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/Dockerfile
      - -t
      - gcr.io/$PROJECT_ID/game28-api-rust
      - .

images:
  - gcr.io/$PROJECT_ID/game28-api-rust